insert into Word (category, val, translated) values ('word', 'hej!', 'ciao!')
insert into Word (category, val, translated) values ('word', 'katt', 'gatto')
insert into Word (category, val, translated) values ('word', 'nyckel', 'chiave')
insert into Word (category, val, translated) values ('word', 'vi åker', 'andiamo')
insert into Word (category, val, translated) values ('word', 'och', 'e')
insert into Word (category, val, translated) values ('word', 'du', 'tu')
insert into Word (category, val, translated) values ('word', 'jag också', 'anch’io')
insert into Word (category, val, translated) values ('word', 'detta', 'questa (f)')
insert into Word (category, val, translated) values ('word', 'är', 'è')
insert into Word (category, val, translated) values ('word', 'lärare', 'insegnante')
insert into Word (category, val, translated) values ('word', 'fru, frun', 'signora')
insert into Word (category, val, translated) values ('word', 'ursäkta', 'scusi')
insert into Word (category, val, translated) values ('word', 'ert', 'il suo')
insert into Word (category, val, translated) values ('word', 'namn', 'nome')
insert into Word (category, val, translated) values ('word', 'tack (eng. please)', 'per favore')
insert into Word (category, val, translated) values ('word', 'min', 'mio (m)')
insert into Word (category, val, translated) values ('word', 'son', 'figlio')
insert into Word (category, val, translated) values ('word', 'hund', 'cane')
insert into Word (category, val, translated) values ('word', 'ryggsäck', 'zaino')
insert into Word (category, val, translated) values ('word', 'adress', 'indirizzo')
insert into Word (category, val, translated) values ('word', 'smink', 'trucco')
insert into Word (category, val, translated) values ('word', 'badrum', 'bagno')
insert into Word (category, val, translated) values ('word', 'skog', 'bosco')
insert into Word (category, val, translated) values ('word', 'tidning', 'giornale')
insert into Word (category, val, translated) values ('word', 'biljett', 'biglietto')
insert into Word (category, val, translated) values ('word', 'mobil', 'cellulare')
insert into Word (category, val, translated) values ('word', 'fotboll', 'calcio')
insert into Word (category, val, translated) values ('word', 'vem?', 'chi?')
insert into Word (category, val, translated) values ('word', 'ost', 'formaggio')
insert into Word (category, val, translated) values ('word', 'löv', 'foglia')
insert into Word (category, val, translated) values ('word', 'svan', 'cigno')
insert into Word (category, val, translated) values ('word', 'damm', 'stagno')
insert into Word (category, val, translated) values ('word', 'killar och tjejer', 'ragazzi')
insert into Word (category, val, translated) values ('word', 'magistern', 'prof')
insert into Word (category, val, translated) values ('word', 'jättebra', 'benissimo')
insert into Word (category, val, translated) values ('word', 'så där', 'così, così')
insert into Word (category, val, translated) values ('word', 'herr, herrn', 'signore')
insert into Word (category, val, translated) values ('word', 'idag', 'oggi')
insert into Word (category, val, translated) values ('word', 'tyvärr', 'purtroppo')
insert into Word (category, val, translated) values ('word', 'trött', 'stanco (m)')
insert into Word (category, val, translated) values ('word', 'ganska', 'abbastanza')
insert into Word (category, val, translated) values ('word', 'jag mår', 'sto')
insert into Word (category, val, translated) values ('word', 'med', 'con')
insert into Word (category, val, translated) values ('word', 'gris', 'maiale')
insert into Word (category, val, translated) values ('word', 'dåligt', 'male')
insert into Word (category, val, translated) values ('word', 'jul', 'Natale')
insert into Word (category, val, translated) values ('word', 'turistbuss', 'pullman')
insert into Word (category, val, translated) values ('word', 'plats', 'posto')
insert into Word (category, val, translated) values ('word', 'ledig', 'libero')
insert into Word (category, val, translated) values ('word', 'inte', 'non')
insert into Word (category, val, translated) values ('word', 'eller hur?', 'vero?')
insert into Word (category, val, translated) values ('word', 'bara', 'solo')
insert into Word (category, val, translated) values ('word', 'lite', 'un po’')
insert into Word (category, val, translated) values ('word', 'fotbollsspelare', 'calciatore')
insert into Word (category, val, translated) values ('word', 'men', 'ma')
insert into Word (category, val, translated) values ('word', 'verkligen', 'davvero')
insert into Word (category, val, translated) values ('word', 'oj då!', 'caspita!')
insert into Word (category, val, translated) values ('word', 'varför?', 'perché?')
insert into Word (category, val, translated) values ('word', 'för, för att', 'per')
insert into Word (category, val, translated) values ('word', 'arbete', 'lavoro')
insert into Word (category, val, translated) values ('word', 'hitta, finna', 'trovare')
insert into Word (category, val, translated) values ('word', 'au pair-flicka', 'ragazza alla pari')
insert into Word (category, val, translated) values ('word', 'familj', 'famiglia')
insert into Word (category, val, translated) values ('word', 'hördu, du! (säg mig)', 'dimmi!')
insert into Word (category, val, translated) values ('word', 'gärna', 'volentieri')
insert into Word (category, val, translated) values ('word', 'när?', 'quando?')
insert into Word (category, val, translated) values ('word', 'vecka', 'settimana')
insert into Word (category, val, translated) values ('word', 'i morgon', 'domani')
insert into Word (category, val, translated) values ('word', 'då', 'allora')
insert into Word (category, val, translated) values ('word', 'heja!', 'forza!')
insert into Word (category, val, translated) values ('word', 'dansa', 'ballare, danzare')
insert into Word (category, val, translated) values ('word', 'flicka', 'bimba')
insert into Word (category, val, translated) values ('word', 'passera', 'passare')
insert into Word (category, val, translated) values ('word', 'folklig dansvisa', 'villanella')
insert into Word (category, val, translated) values ('word', 'vig, rörlig', 'agile')
insert into Word (category, val, translated) values ('word', 'morgon', 'mattino')
insert into Word (category, val, translated) values ('word', 'kväll', 'sera')
insert into Word (category, val, translated) values ('word', 'verka, tyckas', 'sembrare')
insert into Word (category, val, translated) values ('word', 'flyga', 'volare')
insert into Word (category, val, translated) values ('word', 'papegoja', 'papagallo')
insert into Word (category, val, translated) values ('word', 'tryffel', 'tartufo')
insert into Word (category, val, translated) values ('word', 'något', 'qualcosa')
insert into Word (category, val, translated) values ('word', 'här', 'qui')
insert into Word (category, val, translated) values ('word', 'ute, utomhus', 'fuori')
insert into Word (category, val, translated) values ('word', 'terass, uteservering', 'terazza')
insert into Word (category, val, translated) values ('word', 'vad?', 'cosa?')
insert into Word (category, val, translated) values ('word', 'en fylld baguett', 'un panino')
insert into Word (category, val, translated) values ('word', 'en sandwich', 'un tramezzino')
insert into Word (category, val, translated) values ('word', 'det finns', 'c’è')
insert into Word (category, val, translated) values ('word', 'salami', 'salame (m)')
insert into Word (category, val, translated) values ('word', 'skinka', 'prosciutto')
insert into Word (category, val, translated) values ('word', 'is', 'ghiaccio')
insert into Word (category, val, translated) values ('word', 'utan', 'senza')
insert into Word (category, val, translated) values ('word', 'genast', 'subito')
insert into Word (category, val, translated) values ('word', 'jättevacker', 'bellissimo')
insert into Word (category, val, translated) values ('word', 'sant', 'vero')
insert into Word (category, val, translated) values ('word', 'titta!', 'guarda!')
insert into Word (category, val, translated) values ('word', 'båten', 'il batello')
insert into Word (category, val, translated) values ('word', 'där', 'là')
insert into Word (category, val, translated) values ('word', 'senare', 'più tardi')
insert into Word (category, val, translated) values ('word', 'notan', 'conto')
insert into Word (category, val, translated) values ('word', 'ett ögonblick', 'un attimo')
insert into Word (category, val, translated) values ('word', 'snäll, trevlig', 'gentile')
insert into Word (category, val, translated) values ('word', 'jättedyrt', 'carissimo')
insert into Word (category, val, translated) values ('word', 'stackars liten', 'poveretto')
insert into Word (category, val, translated) values ('word', 'alltid', 'sempre')
insert into Word (category, val, translated) values ('word', 'så', 'così')
insert into Word (category, val, translated) values ('word', 'hav', 'mare')
insert into Word (category, val, translated) values ('word', 'vänta!', 'aspetta!')
insert into Word (category, val, translated) values ('word', 'toaletten', 'la toilette')
insert into Word (category, val, translated) values ('word', 'längst in', 'il fondo')
insert into Word (category, val, translated) values ('word', 'fröken', 'signorina')
insert into Word (category, val, translated) values ('word', 'för all del, ingen orsak', 'prego')
insert into Word (category, val, translated) values ('word', 'vad önskas?', 'prego')
insert into Word (category, val, translated) values ('word', 'glas', 'bicchiere')
insert into Word (category, val, translated) values ('word', 'vatten', 'acqua')
insert into Word (category, val, translated) values ('word', 'vin', 'vino')
insert into Word (category, val, translated) values ('word', 'flaska', 'bottiglia')
insert into Word (category, val, translated) values ('word', 'fatöl', 'birra alla spina')
insert into Word (category, val, translated) values ('word', 'juice', 'spremuta')
insert into Word (category, val, translated) values ('word', 'till exempel', 'per esempio')
insert into Word (category, val, translated) values ('word', 'kall', 'freddo')
insert into Word (category, val, translated) values ('word', 'varm', 'caldo')
insert into Word (category, val, translated) values ('word', 'lätt / enkel', 'facile')
insert into Word (category, val, translated) values ('word', 'svår', 'difficile')
insert into Word (category, val, translated) values ('word', 'nåja', 'insomma')
insert into Word (category, val, translated) values ('word', 'regn', 'pioggia')
insert into Word (category, val, translated) values ('word', 'ledsen', 'triste')
insert into Word (category, val, translated) values ('word', 'tillsammans', 'insieme')
insert into Word (category, val, translated) values ('word', 'föräldramöte', 'riunione dei genitori')
insert into Word (category, val, translated) values ('word', 'vanligtvis', 'di solito')
insert into Word (category, val, translated) values ('word', 'trä', 'legno')
insert into Word (category, val, translated) values ('word', 'träd', 'albero')
insert into Word (category, val, translated) values ('word', 'frö', 'seme')
insert into Word (category, val, translated) values ('word', 'sten', 'pietra')
insert into Word (category, val, translated) values ('word', 'gren', 'ramo')
insert into Word (category, val, translated) values ('word', 'dörr', 'una porta')
insert into Word (category, val, translated) values ('word', 'färgpenna', 'matita')
insert into Word (category, val, translated) values ('word', 'sjukhus', 'ospedale')
insert into Word (category, val, translated) values ('word', 'bank', 'banca')
insert into Word (category, val, translated) values ('word', 'tågstation', 'stazione')
--insert into Word (category, val, translated) values ('word', '', '')

insert into Word (category, val, translated) values ('phrase', 'jag beklagar', 'mi dispiace')
insert into Word (category, val, translated) values ('phrase', 'trevligt att träffas', 'piacere')
insert into Word (category, val, translated) values ('phrase', 'varifrån är du?', 'di dove sei?')
insert into Word (category, val, translated) values ('phrase', 'god eftermiddag', 'buonasera')
insert into Word (category, val, translated) values ('phrase', 'god kväll', 'buonasera')
insert into Word (category, val, translated) values ('phrase', 'goddag, godmorgon', 'buongiorno')
insert into Word (category, val, translated) values ('phrase', 'varifrån är Ni?', 'di dov’e?')
insert into Word (category, val, translated) values ('phrase', 'på återseende', 'arrivederci')
insert into Word (category, val, translated) values ('phrase', 'var bor hon?', 'dove abita?')
insert into Word (category, val, translated) values ('phrase', 'varifrån är tjejen?', 'di dov’è la ragazza?')
insert into Word (category, val, translated) values ('phrase', 'vad heter hon?', 'come si chiama?')
insert into Word (category, val, translated) values ('phrase', 'vad gör han?', 'cosa fa?')
insert into Word (category, val, translated) values ('phrase', 'vad heter flickan?', 'come si chiama la ragazza?')
insert into Word (category, val, translated) values ('phrase', 'hur är det?', 'come va?')
insert into Word (category, val, translated) values ('phrase', 'hur mår du?', 'come stai?')
insert into Word (category, val, translated) values ('phrase', 'mycket bra', 'molto bene')
insert into Word (category, val, translated) values ('phrase', 'vi ses imorgon', 'a domani')
insert into Word (category, val, translated) values ('phrase', 'vi ses snart', 'a presto')
insert into Word (category, val, translated) values ('phrase', 'ganska bra (inte illa)', 'non c’è male')
insert into Word (category, val, translated) values ('phrase', 'vi ses', 'ci vediamo')
insert into Word (category, val, translated) values ('phrase', 'på återseende (formellt)', 'arriverderla')
insert into Word (category, val, translated) values ('phrase', 'hur mår Ni?', 'come sta?')
insert into Word (category, val, translated) values ('phrase', 'på den här platsen', 'in questo posto')
insert into Word (category, val, translated) values ('phrase', 'hur kommer det sig att?', 'come mai?')
insert into Word (category, val, translated) values ('phrase', 'bara bekymmer', 'solo guai')
insert into Word (category, val, translated) values ('phrase', 'vill du sjunga med mig?', 'vuoi cantare con me?')
insert into Word (category, val, translated) values ('phrase', 'lycka till!', 'buona fortuna!')
insert into Word (category, val, translated) values ('phrase', 'tack detsamma!', 'grazie altrettanto!')
insert into Word (category, val, translated) values ('phrase', 'lycka till (in i vargens gap)', 'in bocca al lupo!')
insert into Word (category, val, translated) values ('phrase', 'må vargen dö!', 'crepi!')
insert into Word (category, val, translated) values ('phrase', 'varför är du i Italien?', 'perché sei in Italia?')
insert into Word (category, val, translated) values ('phrase', 'för att hitta ett jobb', 'per trovare un lavoro')
insert into Word (category, val, translated) values ('phrase', 'jag är hungrig', 'ho fame')
insert into Word (category, val, translated) values ('phrase', 'ursäkta, notan tack', 'scusi, il conto, per favore')
insert into Word (category, val, translated) values ('phrase', 'jag bjuder!', 'offro io!')
insert into Word (category, val, translated) values ('phrase', 'vänta ett ögonblick', 'aspetta un attimo')
insert into Word (category, val, translated) values ('phrase', 'nej tack, utan is', 'no grazie, senza ghiaccio')
insert into Word (category, val, translated) values ('phrase', 'hur säger man?', 'come si dice?')
insert into Word (category, val, translated) values ('phrase', 'titta (ni) i texten', 'guardate il testo')
insert into Word (category, val, translated) values ('phrase', 'jag kommer genast', 'arrivo subito')
insert into Word (category, val, translated) values ('phrase', 'jag skulle vilja äta något', 'vorrei mangiare qualcosa')
insert into Word (category, val, translated) values ('phrase', 'vi tar något att dricka', 'prendiamo qualcosa da bere')
insert into Word (category, val, translated) values ('phrase', 'vi ses nästa tisdag', 'ci vediamo martedì prossimo')
insert into Word (category, val, translated) values ('phrase', 'jag känner mig dålig/hemsk', 'sto malissimo')
insert into Word (category, val, translated) values ('phrase', 'det är kallt ute', 'fa freddo fuori')
insert into Word (category, val, translated) values ('phrase', 'vi är klara för idag', 'per oggi abbiamo finito')
insert into Word (category, val, translated) values ('phrase', 'vi fortsätter', 'tiriamo avanti')
insert into Word (category, val, translated) values ('phrase', 'mina favoritsmaker är...', 'i miei gusti preferiti sono...')
insert into Word (category, val, translated) values ('phrase', 'vilka är dina favoritsmaker?', 'quali sono i tuoi gusti preferiti?')
insert into Word (category, val, translated) values ('phrase', 'hur mycket kostar det?', 'quanto costa? / quantè?')
insert into Word (category, val, translated) values ('phrase', 'vad konstigt!', 'che strano!')
insert into Word (category, val, translated) values ('phrase', 'jag är törstig', 'ho sete')
insert into Word (category, val, translated) values ('phrase', 'men kom igen!', 'ma dai!')
insert into Word (category, val, translated) values ('phrase', 'jag är riktigt sjuk idag', 'oggi sto proprio male')
insert into Word (category, val, translated) values ('phrase', 'tycker du om att resa?', 'ti piace viaggare?')
insert into Word (category, val, translated) values ('phrase', 'jag tycker om italienska ostar', 'Mi piacciono i formaggi italiani')
insert into Word (category, val, translated) values ('phrase', 'nej, jag gillar det inte alls', 'no, non mi piace per niente')
insert into Word (category, val, translated) values ('phrase', 'du behöver inte skriva', 'non dovete scrivere')
insert into Word (category, val, translated) values ('phrase', 'vi väntar på de andra', 'aspettiamo gli altri')

insert into Word (category, val, translated) values ('phrase', 'min dotter är mörkrädd', 'mia figlia ha paura del buio')
insert into Word (category, val, translated) values ('phrase', 'jag är flygrädd', 'io ho paura di volare')
insert into Word (category, val, translated) values ('phrase', 'det är inte lätt att beställa från barer i Italien', 'non è facile ordinare a bar in Italia')
insert into Word (category, val, translated) values ('phrase', 'vilket år är du född?', 'in che anno sei nato?')
insert into Word (category, val, translated) values ('phrase', 'jag förstod inte', 'non ho capito')
insert into Word (category, val, translated) values ('phrase', 'kan/vill du upprepa?', 'vuoi ripetere?')

insert into Word (category, val, translated) values ('phrase', 'jag är varm', 'ho caldo')
insert into Word (category, val, translated) values ('phrase', 'är du kall?', 'tu hai freddo?')
insert into Word (category, val, translated) values ('phrase', 'vi är rädda', 'abbiamo paura')
insert into Word (category, val, translated) values ('phrase', 'jag är sömnig', 'ho sonno')
insert into Word (category, val, translated) values ('phrase', 'du har rätt', 'hai ragione')
insert into Word (category, val, translated) values ('phrase', 'han har fel', 'ha torto')
insert into Word (category, val, translated) values ('phrase', 'jag behöver ett glas vin', 'ho bisogno di un bicchiere di vino')
insert into Word (category, val, translated) values ('phrase', 'har ni bråttom?', 'avete fretta?')
insert into Word (category, val, translated) values ('phrase', 'de har mycket tålamod', 'hanno molta pazienza')
insert into Word (category, val, translated) values ('phrase', 'var uppmärksam', 'fa attenzione')
insert into Word (category, val, translated) values ('phrase', 'faccio il bagno', 'jag tar ett bad')
insert into Word (category, val, translated) values ('phrase', 'det är varmt', 'fa caldo')
insert into Word (category, val, translated) values ('phrase', 'de äter frukost kl. 7', 'fanno colazione alle 7')
insert into Word (category, val, translated) values ('phrase', 'vi tar en promenad', 'facciamo una passeggiata')
insert into Word (category, val, translated) values ('phrase', 'vi gör ett misstag', 'facciamo un errore')
insert into Word (category, val, translated) values ('phrase', 'du pausar', 'fai una pausa')
insert into Word (category, val, translated) values ('phrase', 'han handlar', 'fa una spesa')
insert into Word (category, val, translated) values ('phrase', 'jag handlar en gång i veckan', 'faccio la spesa una volta a settimana')
insert into Word (category, val, translated) values ('phrase', 'vi badar i havet', 'facciamo il bagno al mare')
insert into Word (category, val, translated) values ('phrase', 'du behöver sova', 'hai bisogno di dormire')
insert into Word (category, val, translated) values ('phrase', 'han gillar det så att han kan dö', 'gli piace da morire')
insert into Word (category, val, translated) values ('phrase', 'hon gillar chocklad', 'le piace il cioccolato')

--insert into Word (category, val, translated) values ('phrase', '', '')

insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'essere', 'sono=är;sei=är;è=är;siamo=är;siete=är;sono=är')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'chiamarsi', 'mi chiamo=heter;ti chiami=heter;si chiama=heter')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'parlare', 'parlo=talar;parli=talar;parla=talar;parliamo=talar;parlate=talar;parlano=talar')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'abitare', 'abito=bor;abiti=bor;abita=bor;abitiamo=bor;abitate=bor;abitano=bor')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'stare', 'sto=mår;stai=mår;sta=mår;stiamo=mår;state=mår;stanno=mår')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'mangiare', 'mangio=äter;mangi=äter;mangia=äter;mangiamo=äter;mangiate=äter;mangiano=äter')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'cenare', 'ceno=äter middag;ceni=äter middag;cena=äter middag;ceniamo=äter middag;cenate=äter middag;cenano=äter middag')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'cantare', 'canto=sjunger;canti=sjunger;canta=sjunger;cantiamo=sjunger;cantate=sjunger;cantano=sjunger')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'amare', 'amo=älskar;ami=älskar;ama=älskar;amiamo=älskar;amate=älskar;amano=älskar')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'ascoltare', 'ascolto=lyssnar;ascolti=lyssnar;ascolta=lyssnar;ascoltiamo=lyssnar;ascoltate=lyssnar;ascoltano=lyssnar')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'lavorare', 'lavoro=arbetar;lavori=arbetar;lavora=arbetar;lavoriamo=arbetar;lavorate=arbetar;lavorano=arbetar')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'guardare', 'guardo=ser;guardi=ser;guarda=se;guardiamo=ser;guardate=ser;guardano=ser')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'prendere', 'prendo=tar;prendi=tar;prende=tar;prendiamo=tar;prendete=tar;prendono=tar')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'volere', 'voglio=vill;vuoi=vill;vuole=vill;vogliamo=vill;volete=vill;vogliono=vill')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'avere', 'ho=har;hai=har;ha=har;abbiamo=har;avete=har;hanno=har')
insert into Verb (modality, tense, val, conjugation_list) values ('INDICATIVE', 'PRESENT', 'fare', 'faccio=gör;fai=gör;fa=gör;facciamo=gör;fate=gör;fanno=gör')
